apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  application.yml: |
    server:
      port: 8081
    spring:
      application:
        name: api-gateway
      cloud:
        gateway:
          routes:
            - id: auth-server-route
              uri: http://auth-server:8080
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=1
            - id: joke-service-route
              uri: http://joke-service:8082
              predicates:
                - Path=/api/joke/**
              filters:
                - StripPrefix=1
                - JwtValidationFilterFactory
            - id: quote-service-route
              uri: http://quote-service:8083
              predicates:
                - Path=/api/quote/**
              filters:
                - StripPrefix=1
                - JwtValidationFilterFactory
    management:
      endpoints:
        web:
          exposure:
            include: health,info
      endpoint:
        health:
          show-details: always 